---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
  labels:
    app.kubernetes.io/name: chaos-engineering-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-engineering-lab-runner
  namespace: chaos-testing
  labels:
    app.kubernetes.io/name: chaos-engineering-lab
    app.kubernetes.io/component: runner
